name: VM Manager CI

on: [push, pull_request]
permissions: read-all
jobs:
  build_ubuntu_gcc:

    runs-on: ${{ matrix.os }}
    env:
      LOCAL_INSTALL_DIR: ${{ github.workspace }}/.local
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
        with:
          path: vm-manager
          fetch-depth: 0

      - name: setup
        run: |
          sudo apt-get --quiet update --yes
          sudo apt-get --quiet install --yes make devscripts lintian debhelper
          sudo apt-get --quiet install --yes autoconf libtool pkg-config
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          gcc --version
          cmake --version
          which cmake

      - name: build
        run: |
          export PATH="${{ env.LOCAL_INSTALL_DIR }}/bin:$PATH"
          sudo ln -s $(which cmake) /usr/bin/cmake || echo ""
          cd vm-manager/
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          debuild --preserve-env -b -uc -us --lintian-opts --profile debian

      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vm-manager.${{ matrix.os }}.${{ github.run_id }}.${{ github.sha }}
          path: |
            ${{ github.workspace }}/vm-manager/debian/
            *.deb
            *.ddeb
            *.build
            *.buildinfo
            *.changes
